### PR TITLE
add mutex to prevent callback and scheduling of callback from running at the same time                      

### PR DESCRIPTION
**Pull request by bsobhani**
This is to fix an apparent bug where pydev.iointr sometimes randomly sets the record value to 0 instead of the commanded value.

Here is a camonitor of some records whose value (for testing purposes) I was forcing to 5 via "pydev.iointr('interrupt_name', 5)":

```
BL100:DH1:FitPeak1:mu          <undefined> 0 UDF INVALID
BL100:DH1:FitPeak1:sigma       <undefined> 0 UDF INVALID
BL100:DH1:FitPeak1:mu          2023-08-14 17:43:28.540899 5  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:43:28.540962 5  
BL100:DH1:FitPeak1:mu          2023-08-14 17:43:48.937786 0  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:43:48.937853 0  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:43:53.866330 5  
BL100:DH1:FitPeak1:mu          2023-08-14 17:43:53.866379 5  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:44:49.731883 0  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:44:54.812919 5  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:45:35.569960 0  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:45:40.684354 5  
BL100:DH1:FitPeak1:mu          2023-08-14 17:45:50.661259 0  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:45:50.661336 0  
BL100:DH1:FitPeak1:mu          2023-08-14 17:45:55.894239 5  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:46:00.928380 5  
BL100:DH1:FitPeak1:mu          2023-08-14 17:46:11.022913 0  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:46:11.022986 0  
BL100:DH1:FitPeak1:mu          2023-08-14 17:46:16.110062 5  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:46:21.236704 5  
BL100:DH1:FitPeak1:mu          2023-08-14 17:46:36.530298 0  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:46:36.530371 0  
BL100:DH1:FitPeak1:mu          2023-08-14 17:46:41.669093 5  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:46:41.672415 5  
BL100:DH1:FitPeak1:mu          2023-08-14 17:46:46.643396 0  
BL100:DH1:FitPeak1:mu          2023-08-14 17:46:51.698989 5  
BL100:DH1:FitPeak1:mu          2023-08-14 17:47:11.818665 0  
BL100:DH1:FitPeak1:mu          2023-08-14 17:47:17.194963 5  
```

Since pydev.iointr was being called only with a value of 5, the value should have been only 5, but instead the behavior we see is that the value flips back and forth between 5 and 0. 

The issue seemed to go away when I added the mutex in the pull request. It seems to me like the issue happens when a callback is being scheduled and a callback is being run at the same time.

### CODE REVIEW

**Comment by klemenv** [comment]
Can you show your 2 records and the python code? Are both records using the same I/O intr name? Does behavior change with only one record subscribed to interrupts?

For a test, can you try to remove your second lock around the scheduling, and leave just the one around cb?

**Comment by bsobhani** [comment]
>Can you show your 2 records and the python code? 

The records are:

```
record(ai, "$(P)$(R)FitPeak$(N):mu"){
field(SCAN, "I/O Intr")
field(INP,  "@pydev.iointr('$(LP)pf$(N)_mu')")
#field(SCAN, "Passive")
#field(INP,  "@$(LP)pf$(N).mu_intr")
field(DTYP, "pydev")
}
record(ai, "$(P)$(R)FitPeak$(N):sigma"){
field(SCAN, "I/O Intr")
field(INP,  "@pydev.iointr('$(LP)pf$(N)_sigma')")
#field(SCAN, "Passive")
#field(INP,  "@$(LP)pf$(N).sigma_intr")
field(DTYP, "pydev")
}
```



I have a class like this:
```

class ControlPyDev:
        def iointr(self, key, val):
                #time.sleep(random.random())
                #pydev.iointr(key, val)
                pydev.iointr(key, 5) # for testing
                #time.sleep(random.random())
        def set_fitting_error(self, err):
                self.iointr(self.name+"_fitting_error", int(err))
        def set_A(self, val):
                self.iointr(self.name+"_A", val)
        def set_mu(self, val):
                self.iointr(self.name+"_mu", val)
        def set_sigma(self, val):
                self.iointr(self.name+"_sigma", val)
        def set_rms_error(self, val):
                self.iointr(self.name+"_rms_error", val)
        def __init__(self, name):
                self.name = name

```

It's created with the following:

```
self.control = ControlPyDev(name)
```

and then called with:

```
                self.control.set_A(self.A_intr)
                self.control.set_mu(self.mu_intr)
                self.control.set_sigma(self.sigma_intr)
                self.control.set_rms_error(rms_error_intr)
```



>Are both records using the same I/O intr name?

I believe all the records I used with interrupts during testing have unique interrupt names:

```
q8i@bl100-dasopi1:/home/controls/epics/dspacehistory$ caget BL100:DH1:FitPeak1:A.INP
BL100:DH1:FitPeak1:A.INP       @pydev.iointr(\'dh1_pf1_A\')
q8i@bl100-dasopi1:/home/controls/epics/dspacehistory$ caget BL100:DH1:FitPeak2:A.INP
BL100:DH1:FitPeak2:A.INP       @pydev.iointr(\'dh1_pf2_A\')
q8i@bl100-dasopi1:/home/controls/epics/dspacehistory$ caget BL100:DH1:FitPeak3:A.INP
BL100:DH1:FitPeak3:A.INP       @pydev.iointr(\'dh1_pf3_A\')
q8i@bl100-dasopi1:/home/controls/epics/dspacehistory$ caget BL100:DH1:FitPeak1:mu.INP
BL100:DH1:FitPeak1:mu.INP      @pydev.iointr(\'dh1_pf1_mu\')
q8i@bl100-dasopi1:/home/controls/epics/dspacehistory$ caget BL100:DH1:FitPeak2:mu.INP
BL100:DH1:FitPeak2:mu.INP      @pydev.iointr(\'dh1_pf2_mu\')
q8i@bl100-dasopi1:/home/controls/epics/dspacehistory$ caget BL100:DH1:FitPeak3:mu.INP
BL100:DH1:FitPeak3:mu.INP      @pydev.iointr(\'dh1_pf3_mu\')
q8i@bl100-dasopi1:/home/controls/epics/dspacehistory$ caget BL100:DH1:FitPeak1:sigma.INP
BL100:DH1:FitPeak1:sigma.INP   @pydev.iointr(\'dh1_pf1_sigma\')
q8i@bl100-dasopi1:/home/controls/epics/dspacehistory$ caget BL100:DH1:FitPeak2:sigma.INP
BL100:DH1:FitPeak2:sigma.INP   @pydev.iointr(\'dh1_pf2_sigma\')
q8i@bl100-dasopi1:/home/controls/epics/dspacehistory$ caget BL100:DH1:FitPeak3:sigma.INP
BL100:DH1:FitPeak3:sigma.INP   @pydev.iointr(\'dh1_pf3_sigma\')

```

>Does behavior change with only one record subscribed to interrupts?

Yes if comment out 'field(SCAN, "I/O Intr")' for the A and sigma records, and leave it in only for the mu records, the issue seems to go away.

>For a test, can you try to remove your second lock around the scheduling, and leave just the one around cb?

When I did this the issue was still there - it would flip back and forth between 5 and 0.

---

After thinking about this, I am not sure if my pull request is an ideal solution, since I would think that a purpose of the system in the asyncexec file is to be able to schedule a task without wwaitingaiting for the previous one to be completed. 

I am somewhat confused that locking cb() from running at the same time as enqueue seems to work, because it looks like cb is copied before it runs, so I would think calling it would not impact the queue. Maybe the lock is delaying the execution of some other code, and this is the real thing that makes the issue go away.

Another thing I will mention: Instead of putting mutex2 around cb(), I tried putting it around enqueue and dequeue (leaving the original mutex in place) and it seemed to make the issue go away. However, I think the reason it works was because since dequeue() is now completely locked, event.wait would wait until timing out, and this delay was probably long enough for some necessary processing to take place.

**Comment by klemenv** [comment]
self.control.set_A(self.A_intr)
                self.control.set_mu(self.mu_intr)
                self.control.set_sigma(self.sigma_intr)
                self.control.set_rms_error(rms_error_intr)

Some of the timestamps from your original message are very much close together. How are you triggering your Python code? Is there a Python thread that calls self.control.set_* functions?

BL100:DH1:FitPeak1:mu          2023-08-14 17:43:28.540899 5  
BL100:DH1:FitPeak1:sigma       2023-08-14 17:43:28.540962 5 

I'm asking all these question to try to understand your environment. Your patch may fix it for you, but it's not obvious to me how it could affect the behavior, aside from the timing that you also recognized. The queue is thread safe, so is calling the callback() which is a unique object copy which then triggers record processing through epics in a standard way. It is then invoking Python code again to retrieve the value for the record, which should be protected with Python GIL.

**Comment by bsobhani** [comment]
Here is an internal link of where the interrupts are being called:

https://code.ornl.gov/idac/ex/dspacehistory/-/blob/pydev_testing/ADProcessImageApp/peakFitSrc/peak_fit_classes.py#L230

What is triggering the execution of that function which calls the interrupts is the following record:

```
record(pycalc, "$(P)$(R)FitPeak$(N)_pycalc"){
#field(FLNK,  "$(P)$(R)FitPeak$(N):A")
field(MEA, 100000)
field(MEB, 100000)
field(INPA, "$(X_PV)")
field(INPB, "$(Y_PV) CP")
field(CALC, "$(LP)pf$(N).fit_calc(A,B)")
}
```

https://code.ornl.gov/idac/ex/dspacehistory/-/blob/pydev_testing/ADProcessImageApp/Db/FitPeakN.template#L1

In this case, Y_PV is set to a waveform record ($(P)DH1:LastWaveform) that updates every 5 seconds, so this python code is triggered every 5 seconds. But interrupts for mu, A, sigma are called immediately after one another within the python code.

One thing I am noticing is if instead of the mutex, I put a 100ms delay before this line:

https://github.com/klemenv/PyDevice/blob/main/src/pydev_ai.cpp#L122

It also seems to work. But if instead put the delay immediately after this line, the record is 0 all the time (instead of 5) and never changes.

**Comment by bsobhani** [comment]
My apologies for not providing a minimal example - I have trouble reproducing the issue in a simple IOC which leads me to believe the issue may be triggered by things like CPU usage, execution time, or other things.

However, I am able to demonstrate the curious behavior with the delay (which I think may be related) that I mentioned at the end of my last comment using a minimal IOC:

Here is the code with the delay which causes the record to be set to 0 instead of 5:

https://github.com/bsobhani/PyDevice/tree/delay_after_cb_request

And here is the minimal IOC I used to test it:

https://github.com/bsobhani/pydev_test

Without the delay I get:

```
q8i:A                          2023-08-21 18:01:36.494392 5  
q8i:B                          2023-08-21 18:01:36.494405 5  
q8i:C                          2023-08-21 18:01:36.494406 5  
q8i:D                          2023-08-21 18:01:36.494407 5  
q8i2:A                         2023-08-21 18:01:36.494326 5  
q8i2:B                         2023-08-21 18:01:36.494134 5  
q8i2:C                         2023-08-21 18:01:36.494226 5  
q8i2:D                         2023-08-21 18:01:36.494386 5  
q8i3:A                         2023-08-21 18:01:36.494389 5  
q8i3:B                         2023-08-21 18:01:36.494390 5  
q8i3:C                         2023-08-21 18:01:36.494391 5  
q8i3:D                         2023-08-21 18:01:36.494391 5  
```

With the delay I get:

```
q8i:A                          2023-08-21 18:10:52.456094 0  
q8i:B                          2023-08-21 18:10:52.456861 0  
q8i:C                          2023-08-21 18:10:52.556255 0  
q8i:D                          2023-08-21 18:10:52.556281 0  
q8i2:A                         2023-08-21 18:10:52.355819 0  
q8i2:B                         2023-08-21 18:10:52.355835 0  
q8i2:C                         2023-08-21 18:10:52.356735 0  
q8i2:D                         2023-08-21 18:10:52.456042 0  
q8i3:A                         2023-08-21 18:10:52.557099 0  
q8i3:B                         2023-08-21 18:10:52.656419 0  
q8i3:C                         2023-08-21 18:10:52.656437 0  
q8i3:D                         2023-08-21 18:10:52.657221 0  

```

Why would placing a delay there affect the values at all?

Note that despite my interest in this issue there is no urgency with respect to time, so please take your time in responding.

**Comment by bsobhani** [comment]
On one machine I found that the minimal example I posted previously actually does reproduce the issue, with the current main branch of PyDevice (the unnmodified version, without any delay). The resource usage on that machine is heavy (because of other software that is running).

But then I tried running the same minimal example on my laptop, which does not have heavy resource usage, and it did not reproduce the bug.

However, I am able to consistently reproduce the issue of the interrupt setting the record to 0, even on my laptop, with the following setup:

https://github.com/bsobhani/pydev_test/tree/interrupt_zero_demonstration
https://github.com/bsobhani/cpu_consume
https://github.com/klemenv/PyDevice

In one terminal I run cpu_consume, and in another I run the pydev_test ioc (interrupt_zero_demonstration branch). 

This is the behavior I get:

```
q8i2:A                         2023-08-23 18:11:12.480888 5  
q8i2:B                         2023-08-23 18:11:12.480890 5  
q8i2:C                         2023-08-23 18:11:12.480891 5  
q8i2:D                         2023-08-23 18:11:12.480892 5  
q8i3:A                         2023-08-23 18:11:12.480893 5  
q8i3:B                         2023-08-23 18:11:12.480895 5  
q8i3:C                         2023-08-23 18:11:12.481480 5  
q8i3:D                         2023-08-23 18:11:12.481483 5  
q8i:D                          2023-08-23 18:11:23.267609 0  
q8i2:A                         2023-08-23 18:11:23.277933 0  
q8i2:B                         2023-08-23 18:11:23.278087 0  
q8i2:C                         2023-08-23 18:11:23.278231 0  
q8i2:D                         2023-08-23 18:11:23.278333 0  
q8i3:A                         2023-08-23 18:11:23.278431 0  
q8i3:B                         2023-08-23 18:11:23.278525 0  
q8i3:C                         2023-08-23 18:11:23.278618 0  
q8i3:D                         2023-08-23 18:11:23.278712 0  
q8i:D                          2023-08-23 18:11:24.478586 5  
q8i2:A                         2023-08-23 18:11:24.478594 5  
q8i2:B                         2023-08-23 18:11:24.478595 5  
q8i2:C                         2023-08-23 18:11:24.478596 5  
q8i2:D                         2023-08-23 18:11:24.478597 5  
q8i3:A                         2023-08-23 18:11:24.478598 5  
q8i3:B                         2023-08-23 18:11:24.478599 5  
q8i3:C                         2023-08-23 18:11:24.478965 5  
q8i3:D                         2023-08-23 18:11:24.478969 5  
q8i3:D                         2023-08-23 18:11:30.397851 0  
q8i3:D                         2023-08-23 18:11:31.573193 5  
q8i3:D                         2023-08-23 18:11:58.721633 0  
q8i3:D                         2023-08-23 18:11:59.586453 5  
q8i2:C                         2023-08-23 18:12:09.664020 0  
q8i2:D                         2023-08-23 18:12:09.664068 0  
q8i3:A                         2023-08-23 18:12:09.664111 0  
q8i3:B                         2023-08-23 18:12:09.664156 0  
q8i3:C                         2023-08-23 18:12:09.664196 0  
q8i3:D                         2023-08-23 18:12:09.664240 0  
```

**Comment by klemenv** [comment]
Can you try to apply this patch and re-run your tests?

diff --git i/src/pydev_ai.cpp w/src/pydev_ai.cpp
index 47a4fa2..be830f5 100644
--- i/src/pydev_ai.cpp
+++ w/src/pydev_ai.cpp
@@ -119,11 +119,10 @@ static void processRecordCb(aiRecord* rec)
         recGblSetSevr(rec, epicsAlarmCalc, epicsSevInvalid);
         ctx->processCbStatus = -1;
     }
-    callbackRequestProcessCallback(&ctx->callback, rec->prio, rec);
-
-
     if (ctx->processCbStatus == 0)
         ctx->processCbStatus = 2; // No convertion needed
+
+    callbackRequestProcessCallback(&ctx->callback, rec->prio, rec);
 }
 
 static long processRecord(aiRecord* rec)

**Comment by bsobhani** [comment]
Ok, I cloned a fresh copy of pydevice and modified it in this way and this seems to fix the issue - thank you. I let my code run for 4 hours, and it has been holding the value of 5 that is being commanded. Without the patch, the issue comes back after a few minutes of running.

**Comment by klemenv** [comment]
The patch has been committed to main branch as ec1ef37a51f2ca3183c42baafa25c482e4822dc7

**Pull request closed without merging**
