### PR TITLE
Lsi lso

### PR DESCRIPTION
**Pull request by simon-ess**
Adding support for lsi/lso records to PyDevice.

### CODE REVIEW

**Comment by klemenv** [comment]
This is a nice addition. The only thing that stands out the escaping of characters. Can you explain why that is needed, we do have stringin/stringout support which does almost the same thing.

Also, we'll need to wrap the lso/lsi support into #ifdef for the right EPICS version. I think it was somewhere in 3.15 when these records were added.

**Comment by simon-ess** [comment]
If you try to have a record like
```
record(lsi, "name") {
  field(INP, "@foo('%VAL%')")
}
```
if your string has any line breaks, then the python interpreter reads this as
```python
foo('hello
there')
```
which is of course not going to run very well. So we need to escape these so that python instead sees
```python
foo('hello\nthere')
```

**Comment by simon-ess** [comment]
I agree that these should probably be in the stringout/stringin parts as well, but I figured I would start with the part that I am working with before adding it to other parts of the code :)

**Comment by simon-ess** [comment]
Regarding the #ifdef for the EPICS version, oof, that makes this a bit annoying with respect to the .dbd file as well then, doesn't it?

**Comment by klemenv** [comment]
I don't see a problem with 
```
foo('hello
there')
```
if that's what user intended. The unescaped \n can be caught in Python code and interpreted as if the text was read from a file. Similarly for passing new-lined text to the record, why needing to escape it in Python? For example, this works today:
```
  with open(filename, 'r') as f:
    pydev.iointr('log_from_file', f.read())
```
and the stringin record can be simply tied into CSS/Phoebus without any un-escaping.

**Comment by simon-ess** [comment]
I had problems without escaping of using lsi/lso records which contained newlines: the interpreter tried to parse 
```python
foo('hello
there')
```
as two separate lines, which was a syntax error; it didn't even have a chance to get caught by the python code at all, in that sense.

**Comment by klemenv** [comment]
I was able to reproduce your \n problem with stringin as well. I noticed that our logging applications are using waveform which doesn't have this issue, which explains why I wasn't seeing this before. However, let's first merge support for lso/lsi alone and do escaping later for all records that need it. Can you modify the pull request accordingly?

Also, for the dbd, let's call it dev315 instead of devLs.

**Comment by simon-ess** [comment]
I've implemented your suggestions, when this gets merged I will create a new PR with the escaping code and apply it to both stringin/out and lsi/lso.

**Pull request merged**
